//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntTheWumpus {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntTheWumpus.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw figures for get arrow.
        /// </summary>
        internal static string ArrowHintText {
            get {
                return ResourceManager.GetString("ArrowHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have bad luck....
        /// </summary>
        internal static string BadLuckHint {
            get {
                return ResourceManager.GetString("BadLuckHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bat in .
        /// </summary>
        internal static string BatHint {
            get {
                return ResourceManager.GetString("BatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bats Nearby({0}).
        /// </summary>
        internal static string BatWarning {
            get {
                return ResourceManager.GetString("BatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy Arrows.
        /// </summary>
        internal static string BuyArrowsString {
            get {
                return ResourceManager.GetString("BuyArrowsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy Hint.
        /// </summary>
        internal static string BuyHintString {
            get {
                return ResourceManager.GetString("BuyHintString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + {0} coins.
        /// </summary>
        internal static string CoinsLog {
            get {
                return ResourceManager.GetString("CoinsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left mouse button for#moving#Right mouse button for#shot arrow.
        /// </summary>
        internal static string ControlLog {
            get {
                return ResourceManager.GetString("ControlLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrows {0}.
        /// </summary>
        internal static string CountArrowString {
            get {
                return ResourceManager.GetString("CountArrowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coins {0}.
        /// </summary>
        internal static string CountCoinsString {
            get {
                return ResourceManager.GetString("CountCoinsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ps! before call, check active != null.
        /// </summary>
        internal static string DebugScore {
            get {
                return ResourceManager.GetString("DebugScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy.
        /// </summary>
        internal static string Diff1String {
            get {
                return ResourceManager.GetString("Diff1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium.
        /// </summary>
        internal static string Diff2String {
            get {
                return ResourceManager.GetString("Diff2String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard.
        /// </summary>
        internal static string Diff3String {
            get {
                return ResourceManager.GetString("Diff3String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dodger.png/DODGER#Don&apos;t use MiniGame.
        /// </summary>
        internal static string DodgerAchiv {
            get {
                return ResourceManager.GetString("DodgerAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick a cave or enter.
        /// </summary>
        internal static string EnterSeed1 {
            get {
                return ResourceManager.GetString("EnterSeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на your seed.
        /// </summary>
        internal static string EnterSeed2 {
            get {
                return ResourceManager.GetString("EnterSeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на explorer.png/EXPLORER#Enter all rooms of the cave.
        /// </summary>
        internal static string ExplorerAchiv {
            get {
                return ResourceManager.GetString("ExplorerAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;MG1.png/SPEEDY#Finish 1 lvl mini-game in less#than 7 seconds.
        /// </summary>
        internal static string FasterAchiv {
            get {
                return ResourceManager.GetString("FasterAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You received 2 arrows.
        /// </summary>
        internal static string GiveArrowsString {
            get {
                return ResourceManager.GetString("GiveArrowsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hamilton.png/HAMILTON&apos;S DESCRENDANT#Go through all the rooms visiting#each 1 time only.
        /// </summary>
        internal static string HamiltonAchiv {
            get {
                return ResourceManager.GetString("HamiltonAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw figures for get hint!.
        /// </summary>
        internal static string HintHintText {
            get {
                return ResourceManager.GetString("HintHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #Right click to shoot#arrow.
        /// </summary>
        internal static string HintRightClick {
            get {
                return ResourceManager.GetString("HintRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hunter.png/HUNTER#Buy 4 arrows.
        /// </summary>
        internal static string HunterAchiv {
            get {
                return ResourceManager.GetString("HunterAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leaders.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Defeat.
        /// </summary>
        internal static string LoseString {
            get {
                return ResourceManager.GetString("LoseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map&apos;s seed is {0}.
        /// </summary>
        internal static string MapSeedString {
            get {
                return ResourceManager.GetString("MapSeedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You met BAT.
        /// </summary>
        internal static string MetBatString {
            get {
                return ResourceManager.GetString("MetBatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New achievement!.
        /// </summary>
        internal static string NewAchievement {
            get {
                return ResourceManager.GetString("NewAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not enough coins(need {0} more).
        /// </summary>
        internal static string NotEnoughCoins {
            get {
                return ResourceManager.GetString("NotEnoughCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Room {0}.
        /// </summary>
        internal static string NowRoomString {
            get {
                return ResourceManager.GetString("NowRoomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pit in .
        /// </summary>
        internal static string PitHint {
            get {
                return ResourceManager.GetString("PitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pit! Draw figures for survive!.
        /// </summary>
        internal static string PitHintText {
            get {
                return ResourceManager.GetString("PitHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I feel a draft({0}).
        /// </summary>
        internal static string PitWarning {
            get {
                return ResourceManager.GetString("PitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PLAY!.
        /// </summary>
        internal static string PlayButtonText {
            get {
                return ResourceManager.GetString("PlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Precise.png/PRECISE#Score 500 point in the mini-game on#the 1 lvl by drawing .
        /// </summary>
        internal static string PreciseAchiv {
            get {
                return ResourceManager.GetString("PreciseAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MG2.png/REACTIVE#Finish 2 lvl mini-game in#less than 7 seconds.
        /// </summary>
        internal static string Reactivity {
            get {
                return ResourceManager.GetString("Reactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Robin.png/ROBIN HOOD#Buy 8 arrows.
        /// </summary>
        internal static string RobinAchiv {
            get {
                return ResourceManager.GetString("RobinAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sharpeye.png/SHARPEYE#Score 500 point in the mini-game on#the 2 lvl by drawing only 1 figure.
        /// </summary>
        internal static string SharpeyeAchiv {
            get {
                return ResourceManager.GetString("SharpeyeAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shooter.png/SHOOTER#Buy 2 arrows.
        /// </summary>
        internal static string ShooterAchiv {
            get {
                return ResourceManager.GetString("ShooterAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sniper.png/SNIPER#Score 500 point in the mini-game on#the 3 lvl by drawing only 1 figure.
        /// </summary>
        internal static string SniperAchiv {
            get {
                return ResourceManager.GetString("SniperAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step.png/STEP INTO ABYSS#Explore 12 rooms.
        /// </summary>
        internal static string StepAchiv {
            get {
                return ResourceManager.GetString("StepAchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Victory.
        /// </summary>
        internal static string WinString {
            get {
                return ResourceManager.GetString("WinString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wumpus in .
        /// </summary>
        internal static string WumpusHint {
            get {
                return ResourceManager.GetString("WumpusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wumpus! Draw figures for survive.
        /// </summary>
        internal static string WumpusHintText {
            get {
                return ResourceManager.GetString("WumpusHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wumpus run away.
        /// </summary>
        internal static string WumpusRunString {
            get {
                return ResourceManager.GetString("WumpusRunString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I smell a Wumpus!({0}).
        /// </summary>
        internal static string WumpusWarning {
            get {
                return ResourceManager.GetString("WumpusWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your score {0}.
        /// </summary>
        internal static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MG3.png/ZINGER#Finish 3 lvl mini-game in less#than 7 seconds.
        /// </summary>
        internal static string ZingerAchiv {
            get {
                return ResourceManager.GetString("ZingerAchiv", resourceCulture);
            }
        }
    }
}
